baseURL = 'https://felipeasp.github.io/'
languageCode = 'en-us'
title = 'Felipe A. S. Pires | Security & Infra'
theme = 'terminal'

[params]
  themeColor = 'green' 
  showMenuItems = 2 

  [params.logo]
    logoText = 'felipeasp@devstation:~$'
    logoHomeLink = '/'

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "resume.txt"
    url = "/cv"
    weight = 10

  [[menu.main]]
    identifier = "labs"
    name = "./labs_and_writeups"
    url = "/labs"
    weight = 20
